### ISSUE TITLE
WHY scripts GQA task batchsize of VL-T5 and VL-BART is not consistent of the paper?

### ISSUE THREAD

**Issue by alice-cool** [j-min/VL-T5#18]
![image](https://user-images.githubusercontent.com/16870890/155083477-921be349-f727-46f2-bc41-26ca0e5af5cb.png)
![image](https://user-images.githubusercontent.com/16870890/155083749-7648ce5e-9b00-485c-9740-ea3262641cb2.png)

**Comment by j-min** [comment]
Sorry for the confusion. You can use batch_size=240, as shown in the table. By the way, I found the different batch sizes do not result in a meaningful difference in finetuning performances.
