### ISSUE TITLE
code wrong

### ISSUE THREAD

**Issue by Su1008** [j-min/VL-T5#29]
![image](https://user-images.githubusercontent.com/48051151/195974136-27afcb3c-0732-4080-8529-f83e13da7b2f.png)

**Comment by Su1008** [comment]
how to fix？

**Comment by j-min** [comment]
what is the version of your `transformers`? could you please try with `transformers==4.2.1`?

**Comment by Su1008** [comment]
thanks. My fault.

**Comment by JudePark96** [comment]
passing the arguments ``output_attentions=True`` will work on the latest version of transformers.
