### ISSUE TITLE
Checkpoint on COCO captioning pretraining 

### ISSUE THREAD

**Issue by czy-orange** [j-min/VL-T5#9]
Hi Jaemin,
    Thanks for your great work! Both code and paper inspire me a lot. I want to do a little test and I want checkpoint finetuned on coco pretraining. Would you mind providing it? Thanks.

**Comment by shizhediao** [comment]
Same question.
Thanks

**Comment by czy-orange** [comment]
@shizhediao I finetuned the model myself, here's the checkpoint if you need. 
Link: https://pan.baidu.com/s/1o8dtJSnIkfsqg9Zuo_MbOg 
Passwod: ssj5

**Comment by shizhediao** [comment]
Thanks a lot. Have you finetuned on the refcoco task? I got a strange result with VL-T5.

**Comment by czy-orange** [comment]
@shizhediao No, and it looks good when finetuned on COCO caption.

**Comment by saransh03sharma** [comment]
> @shizhediao I finetuned the model myself, here's the checkpoint if you need. Link: https://pan.baidu.com/s/1o8dtJSnIkfsqg9Zuo_MbOg Passwod: ssj5

can you reshare the link

**Comment by czy-orange** [comment]
@saransh03sharma 

https://pan.baidu.com/s/15x89jpo0YTGzaEQ_MHL9NQ?pwd=8mG6 
password：8mG6
